### ISSUE TITLE
Does not support pnpm catalog feature

### ISSUE THREAD

**Issue by gossi** [embroider-build/ember-auto-import#648]
pnpm has this really nice feature, called [catalog](https://pnpm.io/catalogs). That changes the way how you define the versions of your dependency, and using it yields this error message:

```
ember-auto-import was unable to find any copy of itself that satisfies the app's requested range of catalog:ember
```

We use it to define the versions of our ember deps in `pnpm-workspace.yml` as:

```yml
catalogs:
  ember:
    "@ember/optional-features": "^2.1.0"
    "@ember/string": "^4.0.0"
    "@ember/test-helpers": "^3.3.1"
    "@embroider/addon-dev": "^7.0.0"
    "@embroider/addon-shim": "^1.9.0"
    "@embroider/macros": "^1.16.9"
    "@embroider/test-setup": "^4.0.0"
    "@glimmer/component": "^1.1.2"
    "@glimmer/tracking": "^1.1.2"
    "@glint/core": "^1.5.0"
    "@glint/environment-ember-loose": "^1.5.0"
    "@glint/template": "^1.5.0"
    "ember-auto-import": "^2.10.0"
    "ember-cli": "~5.12.0"
    "ember-cli-app-version": "^6.0.1"
    "ember-cli-babel": "^8.2.0"
    "ember-cli-dependency-checker": "^3.3.2"
    "ember-cli-htmlbars": "^6.3.0"
    "ember-cli-inject-live-reload": "^2.1.0"
    "ember-cli-sri": "^2.1.1"
    "ember-load-initializers": "^2.1.2"
    "ember-qunit": "^8.1.0"
    "ember-resolver": "^12.0.1"
    "ember-source": "~5.12.0"
    "ember-source-channel-url": "^3.0.0"
    "ember-try": "^3.0.0"
    "qunit": "^2.22.0"
    "qunit-dom": "^3.2.1"
```

And then in `package.json` looks like so:

```json
{
  "devDependencies": {
    "ember-auto-import": "catalog:ember",
    "ember-cli": "catalog:ember",
  }
}
```

but the one with `ember-auto-import` isn't working. It seems like there is a check against that version number, but can't use pnpm's resolving for the `catalog:` protocol.
